# Generated by Django 4.2.29 on 2026-03-26 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces / Count'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('litres', 'Litres'), ('ml', 'Millilitres (ml)'), ('packs', 'Packs / Boxes'), ('sets', 'Sets')], default='pieces', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pledged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('delivery_location', models.CharField(blank=True, max_length=300)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='ngo.donation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_assignments', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(choices=[('food', 'Food Items'), ('clothing', 'Clothing'), ('hygiene', 'Hygiene & Personal Care'), ('medical', 'Medical Supplies'), ('educational', 'Educational Items'), ('household', 'Household Items'), ('electronics', 'Electronics'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces / Count'), ('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('litres', 'Litres'), ('ml', 'Millilitres (ml)'), ('packs', 'Packs / Boxes'), ('sets', 'Sets')], default='pieces', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='active', max_length=30)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='ngo.donationrequest'),
        ),
    ]
